/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fiore.flowershop.view;

import fiore.flowershop.controller.ProductController;
import fiore.flowershop.controller.PromotionController;
import fiore.flowershop.model.Product;
import fiore.flowershop.model.Promotion;
import fiore.flowershop.util.Queue;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerListModel;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Jasmine
 */
public class AddPromotionINF extends javax.swing.JInternalFrame {

    PromotionController promoController;
    ProductController productController;
    public AddPromotionINF() {
        initComponents();
        promoController = new PromotionController();
        productController = new ProductController();
        loadCmbBox();
        loadSpinners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        productCMB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        discountTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        monthSPIN = new javax.swing.JSpinner();
        yearSPIN = new javax.swing.JSpinner();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Add Promotion");

        jLabel1.setText("Product ID:");

        productCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select product--" }));

        jLabel2.setText("Discount Percentage");

        jLabel3.setText("Promotion Period:");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(discountTF)
                            .addComponent(productCMB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(monthSPIN, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yearSPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(saveBtn)
                        .addGap(18, 18, 18)
                        .addComponent(resetBtn)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(productCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(discountTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(monthSPIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearSPIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(resetBtn))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadSpinners(){
        ArrayList<String> monthStrings = getMonthStrings();
        SpinnerListModel monthModel = new SpinnerListModel(monthStrings);
        monthSPIN.setModel(monthModel);
        Calendar calendar = Calendar.getInstance();
        int currentYear = calendar.get(Calendar.YEAR);
        SpinnerModel yearModel = new SpinnerNumberModel(currentYear,currentYear - 100,currentYear + 100,1);
        yearSPIN.setModel(yearModel);
        yearSPIN.setEditor(new JSpinner.NumberEditor(yearSPIN, "#"));
    }
    
    private void loadCmbBox(){
        Queue<Product> products = productController.getAllProducts();
        Product productArr[] = products.getQueue(Product.class);
        for(Product p : productArr){
            DefaultComboBoxModel<Product> model = (DefaultComboBoxModel)productCMB.getModel();
            model.addElement(p);
        }
    }
    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        discountTF.setText("");
        productCMB.setSelectedIndex(0);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String productID = "";
        if(productCMB.getSelectedIndex() != 0){
            Product prod = (Product) productCMB.getSelectedItem();
            productID = prod.getProductID();
        }
        
        String discount = discountTF.getText();
        String monthStr = (String) monthSPIN.getValue();
        int month = getMonthInt(monthStr);
        int year = (Integer) yearSPIN.getValue();
        
        String monthstring;
        if(month < 10){
            monthstring = "0" + month;
        }else{
            monthstring = "" + month;
        }
        String my = year + "-" + monthstring;
        
        int ok = 1;
        
        String err = "";
        if(discount.equals("") || productCMB.getSelectedIndex() == 0){
            ok = 0;
            err += "All fields must be filled.";
        }
        
        if(!discount.equals("")){
            try{
                double value = Double.parseDouble(discount);
            }catch(Exception e){
                ok = 0;
                err += " Price must contain only numbers.";
            }
        }
        
        double dc = Double.parseDouble(discount);
        
        if(dc < 1 || dc > 99){
            ok = 0;
            err += " Discount must range from 1% to 99%";
        }
        
        if(ok == 1){
            Promotion p = new Promotion();
            Product prod = new Product();
            prod.setProductID(productID);
            p.setProductID(prod);
            p.setDiscount(Double.parseDouble(discount));
            p.setPromoName("-");
            p.setMonthyear(my);
            String result = promoController.addPromotion(p);
        
            if(result.equals("success")){
                JOptionPane.showMessageDialog(this, "New Promotion Added Successfully ", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, err, "Error", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_saveBtnActionPerformed

    private ArrayList<String> getMonthStrings() {
        LocalDate today = LocalDate.now();
        String[] months = new java.text.DateFormatSymbols().getMonths();
        ArrayList<String> monthStrings = new ArrayList<String>();
        
        for(int m = (today.getMonthValue() - 1); m < (months.length-1); m++){
            String month = months[m];
            monthStrings.add(months[m]);
        }
        return monthStrings;
    }
    
    private int getMonthInt(String monthString){
        int month = 0;
        switch (monthString) {
            case "January":  month = 1;
                     break;
            case "February":  month = 2;
                     break;
            case "March":  month = 3;
                     break;
            case "April":  month = 4;
                     break;
            case "May":  month = 5;
                     break;
            case "June":  month = 6;
                     break;
            case "July":  month = 7;
                     break;
            case "August":  month = 8;
                     break;
            case "September":  month = 9;
                     break;
            case "October": month = 10;
                     break;
            case "November": month = 11;
                     break;
            case "December": month = 12;
                     break;
            default: month = 0;
                     break;
        }
        return month;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField discountTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner monthSPIN;
    private javax.swing.JComboBox<String> productCMB;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JSpinner yearSPIN;
    // End of variables declaration//GEN-END:variables
}
