/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fiore.flowershop.view;

import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Jasmine
 */
public class MainUI extends javax.swing.JFrame {

    AddProductINF addProductINF;
    ViewProductsINF viewProductINF;
    PickUpListINF pickupINF;
    DeliveryListINF deliverINF;
    AddOrderINF addorderINF;
    AddPromotionINF addPromoINF;
    ViewMonthlyPromotion viewPromoINF;
    FloralArrangementINF floralINF;
    
    public MainUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        pickUpMenu = new javax.swing.JMenuItem();
        deliveryMenu = new javax.swing.JMenuItem();
        newOrderMenu = new javax.swing.JMenuItem();
        floralMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addProdMenu = new javax.swing.JMenuItem();
        viewProdMenu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        addPromoMenu = new javax.swing.JMenuItem();
        viewPromoMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1))
        );

        jMenu1.setText("Orders");

        pickUpMenu.setText("Today Pick Up List");
        pickUpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickUpMenuActionPerformed(evt);
            }
        });
        jMenu1.add(pickUpMenu);

        deliveryMenu.setText("Today Delivery List");
        deliveryMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryMenuActionPerformed(evt);
            }
        });
        jMenu1.add(deliveryMenu);

        newOrderMenu.setText("New Order");
        newOrderMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newOrderMenuActionPerformed(evt);
            }
        });
        jMenu1.add(newOrderMenu);

        floralMenu.setText("Custom Floral Arrangement");
        floralMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floralMenuActionPerformed(evt);
            }
        });
        jMenu1.add(floralMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Product");

        addProdMenu.setText("Add Product");
        addProdMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProdMenuActionPerformed(evt);
            }
        });
        jMenu2.add(addProdMenu);

        viewProdMenu.setText("View Product Catalog");
        viewProdMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProdMenuActionPerformed(evt);
            }
        });
        jMenu2.add(viewProdMenu);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Promotion");

        addPromoMenu.setText("Add Promotion");
        addPromoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPromoMenuActionPerformed(evt);
            }
        });
        jMenu3.add(addPromoMenu);

        viewPromoMenu.setText("View Promotion Catalog");
        viewPromoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPromoMenuActionPerformed(evt);
            }
        });
        jMenu3.add(viewPromoMenu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addProdMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProdMenuActionPerformed
        disposeFrames();
        addProductINF = new AddProductINF();
        jDesktopPane1.add(addProductINF);
        addProductINF.setVisible(true);
    }//GEN-LAST:event_addProdMenuActionPerformed

    private void viewProdMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProdMenuActionPerformed
        disposeFrames();
        viewProductINF = new ViewProductsINF();
        jDesktopPane1.add(viewProductINF);
        viewProductINF.setVisible(true);
    }//GEN-LAST:event_viewProdMenuActionPerformed

    private void pickUpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickUpMenuActionPerformed
        disposeFrames();
        pickupINF = new PickUpListINF();
        jDesktopPane1.add(pickupINF);
        pickupINF.setVisible(true);
    }//GEN-LAST:event_pickUpMenuActionPerformed

    private void newOrderMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newOrderMenuActionPerformed
        disposeFrames();
        addorderINF = new AddOrderINF();
        jDesktopPane1.add(addorderINF);
        addorderINF.setVisible(true);
    }//GEN-LAST:event_newOrderMenuActionPerformed

    private void addPromoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPromoMenuActionPerformed
        disposeFrames();
        addPromoINF = new AddPromotionINF();
        jDesktopPane1.add(addPromoINF);
        addPromoINF.setVisible(true);
    }//GEN-LAST:event_addPromoMenuActionPerformed

    private void viewPromoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPromoMenuActionPerformed
        disposeFrames();
        viewPromoINF = new ViewMonthlyPromotion();
        jDesktopPane1.add(viewPromoINF);
        viewPromoINF.setVisible(true);
    }//GEN-LAST:event_viewPromoMenuActionPerformed

    private void floralMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floralMenuActionPerformed
        disposeFrames();
        floralINF = new FloralArrangementINF();
        jDesktopPane1.add(floralINF);
        floralINF.setVisible(true);
    }//GEN-LAST:event_floralMenuActionPerformed

    private void deliveryMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryMenuActionPerformed
        disposeFrames();
        deliverINF = new DeliveryListINF();
        jDesktopPane1.add(deliverINF);
        deliverINF.setVisible(true);
    }//GEN-LAST:event_deliveryMenuActionPerformed

    private void disposeFrames(){
        if(addProductINF !=null){
           addProductINF.dispose();
        }
        if(viewProductINF !=null){
           viewProductINF.dispose();
        }
        if(pickupINF !=null){
           pickupINF.dispose();
        }
        if(deliverINF !=null){
           deliverINF.dispose();
        }
        if(addorderINF !=null){
           addorderINF.dispose();
        }
        if(addPromoINF !=null){
           addPromoINF.dispose();
        }
        if(viewPromoINF !=null){
           viewPromoINF.dispose();
        }
        if(floralINF !=null){
           floralINF.dispose();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addProdMenu;
    private javax.swing.JMenuItem addPromoMenu;
    private javax.swing.JMenuItem deliveryMenu;
    private javax.swing.JMenuItem floralMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem newOrderMenu;
    private javax.swing.JMenuItem pickUpMenu;
    private javax.swing.JMenuItem viewProdMenu;
    private javax.swing.JMenuItem viewPromoMenu;
    // End of variables declaration//GEN-END:variables
}
